# Generated by Django 3.1 on 2020-10-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('subs', models.IntegerField(default=0)),
                ('subs_at', models.IntegerField(default=0)),
                ('posts', models.IntegerField(default=0)),
                ('desc', models.CharField(blank=True, default='This User is Too Lazy to do Descriprion', max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('online', models.BooleanField(default=False)),
            ],
        ),
    ]
