# Generated by Django 3.1 on 2020-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Picture')),
                ('description', models.CharField(max_length=300, verbose_name='Description')),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
