# Generated by Django 3.1 on 2020-10-05 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clone', '0002_auto_20201005_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='USER'),
            preserve_default=False,
        ),
    ]
